# Generated by Django 4.2.7 on 2023-11-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_test_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, through='myapp.Question', to='myapp.test'),
        ),
    ]
